asset_dir = "assets"
exclude_assets = ["*.luau", "*.rbxm"]
write_dir = "assets"
version = 2

[creator]
type = "group"
id = 34745901

[codegen]
output_name = "init"
typescript = false
style = "nested"
strip_extension = true

[inputs.assets]
path = "assets/**/*"
output_path = "src/ReplicatedStorage/Assets"
