[package]
name = "rogershi/main"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ReactSpring = "chriscerie/react-spring@2.0.0"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
React = "jsdotlua/react@17.2.1"
