local assets = {
	Egypt = {
		["Akhenaten.png"] = "rbxassetid://140319991588251",
		["Cleopatra.png"] = "rbxassetid://137545520172915",
		["Narmer.png"] = "rbxassetid://123302243147194",
		["Ptolemy.png"] = "rbxassetid://84772192162069",
		["Rammeses.png"] = "rbxassetid://115676624628103",
		["Tut.png"] = "rbxassetid://127377869922808",
	},
	audio = {
		["explosion.mp3"] = "rbxassetid://133965358324268",
	},
	images = {
		["GreecePhoto.png"] = "rbxassetid://140359005328317",
	},
}

return assets