local assets = {
	Egypt = {
		["Akhenaten.png"] = "rbxassetid://140319991588251",
		["Cleopatra.png"] = "rbxassetid://137545520172915",
		["Narmer.png"] = "rbxassetid://123302243147194",
		["Ptolemy.png"] = "rbxassetid://84772192162069",
		["Rammeses.png"] = "rbxassetid://115676624628103",
		["Tut.png"] = "rbxassetid://127377869922808",
	},
	audio = {
		["657948__lilmati__family-friendly-inspect-sound-ui-or-in-game-notification.wav"] = "rbxassetid://72255888882620",
		["explosion.mp3"] = "rbxassetid://133965358324268",
		["lobby2.mp3"] = "rbxassetid://73590791751799",
	},
	images = {
		["Cao_Cao.png"] = "rbxassetid://73915227461302",
		["GreecePhoto.png"] = "rbxassetid://140359005328317",
		["Qin_Shi_Huang.png"] = "rbxassetid://72049353436342",
		["calendar.png"] = "rbxassetid://118717037434015",
		["person.png"] = "rbxassetid://95049959452468",
		["quest.png"] = "rbxassetid://126483259351802",
	},
}

return assets