--!strict

-- By Wa1er_God --

local Constants = {
	BOOTHTOUCHDELAY = 0.5,
	BOOTHMAPCHOSETIME = 15,
	BOOTHWAITTIME = 15,
	BOOTHRELOADWAITTIME = 5,

	BEZIERCURVE = 5,

	INFORMATIONHASHMAP = "TOWERDEFENCEHASHMAP",

	UpdateDelay = 100,
	LevelXPStore = "LevelXPStorev0.01",
	TotalGoldStore = "TotalGoldv0.01",
	RobuxSpentStore = "RobuxSpentStorev0.01",

	WarningTime = 3,
	CostDivider = 3,

	ROLLDELAYTIME = 3,
	STARTCOINS = 500,
	ROLLCOSTS = { MAIN = 40 },
	ROLLPERCENT = 1,
}

return Constants
