--!strict

-- By Wa1er_God --

local Tips = {
	"Did you know you can use the 'Shift' key to sprint?",
	"Some enemies are weak to specific damage types. Experiment to find their vulnerabilities!",
	"You can upgrade your towers by clicking on them and selecting the upgrade option.",
	"Use the environment to your advantage! Some towers have special effects based on their placement.",
	"Don't forget to check your resources! You need enough currency to build and upgrade towers.",
}

return table.freeze(Tips)
