--!strict

-- By Wa1er_God --

local Constants = {
	INVENTORY_FRAME = "InventoryFrame",
	TRADE_FRAME = "TradeFrame",
	TRADE_MENU = "TradeMenu",
	STORY_FRAME = "StoryFrame",
	ROLL_FRAME = "RollFrame",
	IN_ROLL = "InRoll",
	SETTINGS = "Settings",
	STORE = "Store",
	DAILY_FRAME = "DailyFrame",
	TITLES_FRAME = "TitlesFrame",
	QUESTS_FRAME = "QuestsFrame",
	STARTER_CHOOSE = "StarterChoose",
}

return Constants
